from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Iterable, Protocol, runtime_checkable

from acquirium.internals.models import Order, TimeseriesInfo


@runtime_checkable
class TimeseriesStore(Protocol):
    """Minimal storage contract for timeseries and soft sensor bookkeeping."""

    db_path: str | Path | None

    # table management
    def ensure_table(self) -> str: ...

    # stream handles
    def ensure_stream_handle(self, uri: str, handle: str | None = None) -> str: ...
    def resolve_handle(self, handle_or_uri: str) -> str: ...

    # timeseries mutations and reads
    def upsert_rows(self, point_uri: str, rows: Iterable[tuple[datetime, Any]]) -> int: ...
    def replace_rows(self, point_uri: str, rows: Iterable[tuple[datetime, Any]]) -> int: ...
    def timeseries(
        self,
        point_uri: str,
        *,
        start: datetime | None = None,
        end: datetime | None = None,
        limit: int | None = None,
        order: Order = "asc",
    ) -> list[dict[str, Any]]: ...
    def timeseries_info(self, point_uri: str) -> TimeseriesInfo: ...

    # soft sensor catalog and runs
    def upsert_soft_sensor(self, *, uri: str, module_path: str, sources: list[str], params: dict | None, schedule: str | None) -> None: ...
    def list_soft_sensors(self) -> list[dict[str, Any]]: ...
    def get_soft_sensor(self, uri: str) -> dict[str, Any] | None: ...
    def record_soft_run(self, uri: str, started: datetime, duration_ms: float, rows_out: int, status: str, message: str | None = None) -> None: ...
    def delete_soft_sensor(self, uri: str) -> None: ...

    # transaction-ish hooks
    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

    # utility
    def sql_query(self, query: str) -> dict[str, Any]: ...
    def close(self) -> None: ...
