from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Iterable, Iterator
import hashlib

import psycopg
from psycopg import sql
from psycopg.types.json import Json

from acquirium.internals.models import Order, TimeseriesInfo, TimeInterval, LogEntry, TimeIntervalModel, compute_ref_uri
from acquirium.Storage.base import TimeseriesStore
import logging
import pyarrow as pa
import polars as pl
from rdflib import URIRef
from acquirium.Storage.values import (
    normalize_value_kind,
    normalize_value_mode,
    prepare_value_columns,
    typed_value_series,
)
from acquirium.internals._log import timed_debug

logger = logging.getLogger(__name__)

TIMESERIES_TABLE = "timeseries"
STREAMS_TABLE = "streams"
LOGS_TABLE = "logs"
REF_IDS_TABLE = "ref_ids"
TIMESERIES_STREAMS_VIEW = "timeseries_streams"

# Storage keys: the API speaks ``ref_uri`` strings throughout, but the
# ``timeseries`` hypertable keys rows by an ``INTEGER ref_id`` -- the rows are
# narrower, the unique index and compressed-chunk segmentby work on a 4-byte
# key instead of a TEXT one, and it matches the DuckDB backend. The
# ``ref_ids`` table maps each ``ref_uri`` to its ``ref_id``; ids are assigned
# on first write and resolved inside this module, never exposed. The
# ``timeseries_streams`` view joins the string back in, so SQL against the
# view is unaffected. Databases whose ``timeseries`` table is still keyed by
# ``ref_uri`` are not migrated in place: ``ensure_table`` refuses them, and
# they should be recreated.


class TimescaleStore(TimeseriesStore):
    def __init__(
        self,
        *,
        dsn: str | None = None,
        connect_timeout: int | None = None,
        recreate: bool = False,
    ):
        self.dsn = dsn
        self.db_path = self.dsn
        # default autocommit so reads don't hold open transactions; explicit begin toggles off
        logger.debug("TimescaleStore.__init__: connecting (recreate=%s)", recreate)
        with timed_debug(logger, "psycopg.connect"):
            self.conn = psycopg.connect(self.dsn, autocommit=True, connect_timeout=connect_timeout)
        self._in_tx = False
        if recreate:
            logger.debug("TimescaleStore.__init__: dropping existing tables/views")
            with self.conn.cursor() as cur:
                cur.execute(sql.SQL("DROP VIEW IF EXISTS {} CASCADE").format(sql.Identifier(TIMESERIES_STREAMS_VIEW)))
                cur.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(sql.Identifier(TIMESERIES_TABLE)))
                cur.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(sql.Identifier(REF_IDS_TABLE)))
                cur.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(sql.Identifier(STREAMS_TABLE)))
                cur.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(sql.Identifier(LOGS_TABLE)))
        self.ensure_table()
        logger.debug("TimescaleStore.__init__: ready")

    # -------------------- table management --------------------
    def ensure_table(self) -> str:
        with timed_debug(logger, "ensure_table"), self.conn.cursor() as cur:
            cur.execute("CREATE EXTENSION IF NOT EXISTS timescaledb;")
            # A timeseries table from before ref_id keys would survive the
            # CREATE IF NOT EXISTS below and fail later on the missing column;
            # refuse it here with a message that says what to do.
            cur.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = %s AND column_name = 'ref_uri'
                """,
                (TIMESERIES_TABLE,),
            )
            if cur.fetchone():
                raise RuntimeError(
                    f"{TIMESERIES_TABLE} is keyed by ref_uri; this version keys it by "
                    f"ref_id. Recreate the store (recreate=True) instead of opening it in place."
                )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {REF_IDS_TABLE} (
                    ref_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    ref_uri TEXT NOT NULL UNIQUE
                );
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {TIMESERIES_TABLE} (
                    ref_id INTEGER NOT NULL,
                    ts TIMESTAMPTZ NOT NULL,
                    numeric_value DOUBLE PRECISION,
                    text_value TEXT,
                    CHECK (numeric_value IS NULL OR text_value IS NULL)
                );
                """
            )
            # Create hypertable before enabling Timescale features. We target
            # new Acquirium-managed stores here; older point_uri/handle schemas
            # should be recreated rather than migrated in-place.
            cur.execute(
                sql.SQL(
                    "SELECT create_hypertable(%s, %s, if_not_exists => TRUE);"
                ),
                (TIMESERIES_TABLE, "ts"),
            )
            # Unique index supports idempotent upserts and scans by stream/time.
            # Timescale unique indexes on hypertables must include the time
            # partition column; (ref_id, ts) satisfies that requirement.
            cur.execute(
                f"CREATE UNIQUE INDEX IF NOT EXISTS idx_timeseries_ref_ts_unique ON {TIMESERIES_TABLE} (ref_id, ts);"
            )
            # Segment compressed chunks by stream and order newest-first within
            # each stream. This matches the common "latest values" read path
            # while still supporting ascending scans via reverse index scans.
            cur.execute(
                f"""
                ALTER TABLE {TIMESERIES_TABLE}
                SET (
                    timescaledb.compress,
                    timescaledb.compress_segmentby = 'ref_id',
                    timescaledb.compress_orderby = 'ts DESC'
                );
                """
            )
            cur.execute(
                sql.SQL("SELECT add_compression_policy({}, INTERVAL '7 days', if_not_exists => TRUE);").format(
                    sql.Literal(TIMESERIES_TABLE)
                )
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {STREAMS_TABLE} (
                    ref_uri TEXT PRIMARY KEY,
                    point_uri TEXT,
                    source_id TEXT NOT NULL,
                    ref_name TEXT NOT NULL,
                    value_kind TEXT NOT NULL DEFAULT 'text'
                );
                """
            )
            cur.execute(
                f"ALTER TABLE {STREAMS_TABLE} ALTER COLUMN point_uri DROP NOT NULL;"
            )
            cur.execute(
                f"CREATE UNIQUE INDEX IF NOT EXISTS idx_streams_source_ref_name ON {STREAMS_TABLE} (source_id, ref_name);"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_streams_point_uri ON {STREAMS_TABLE} (point_uri) WHERE point_uri IS NOT NULL;"
            )
            cur.execute(
                f"""
                CREATE OR REPLACE VIEW {TIMESERIES_STREAMS_VIEW} AS
                SELECT
                    r.ref_uri,
                    s.point_uri,
                    s.source_id,
                    s.ref_name,
                    COALESCE(s.value_kind, 'text') AS value_kind,
                    t.ts,
                    t.numeric_value AS value_numeric,
                    t.text_value AS value_text
                FROM {TIMESERIES_TABLE} AS t
                JOIN {REF_IDS_TABLE} AS r
                    ON t.ref_id = r.ref_id
                LEFT JOIN {STREAMS_TABLE} AS s
                    ON r.ref_uri = s.ref_uri;
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {LOGS_TABLE} (
                    point_uri TEXT NOT NULL,
                    timestamp TIMESTAMPTZ NOT NULL,
                    observed tstzrange,
                    message TEXT NOT NULL
                );
                """
            )
            # index to support lookups by point_uri, timestamp
            cur.execute(
                f"CREATE UNIQUE INDEX IF NOT EXISTS idx_logs_point_time ON {LOGS_TABLE} (point_uri, timestamp);"
            )
            # index to support lookups by observed time range
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_logs_observed ON {LOGS_TABLE} USING GIST (observed);"
            )
        if not self._in_tx:
            self.conn.commit()
        return TIMESERIES_TABLE

    # -------------------- storage keys --------------------
    def _ref_id(self, cur, ref_uri: str) -> int | None:
        """Return the ref_id assigned to ref_uri, or None if it was never written."""
        cur.execute(
            f"SELECT ref_id FROM {REF_IDS_TABLE} WHERE ref_uri = %s",
            (ref_uri,),
        )
        row = cur.fetchone()
        return row[0] if row else None

    # -------------------- mutations --------------------
    # Every write goes through one path: the rows become a Polars frame, the
    # frame is COPYed into a TEMP staging table on this connection, ids are
    # assigned for unseen uris, and one INSERT ... SELECT ... ON CONFLICT
    # merges into the hypertable. All of that runs in a single transaction,
    # so a failure leaves neither ids without rows nor a leaked staging
    # table, and inside a begin()/commit() span the write joins that span.
    STAGING_TABLE = "_acquirium_incoming_timeseries"

    def upsert_rows(
        self,
        ref_uri: str,
        rows: Iterable[tuple[datetime, Any]],
        *,
        value_kind: str = "text",
    ) -> int:
        rows_list = list(rows)
        logger.debug("upsert_rows ref_uri=%s rows=%d kind=%s", ref_uri, len(rows_list), value_kind)
        if not rows_list:
            return 0
        return self.bulk_insert_polars(self._rows_frame(ref_uri, rows_list, value_kind))

    def replace_rows(
        self,
        ref_uri: str,
        rows: Iterable[tuple[datetime, Any]],
        *,
        value_kind: str = "text",
    ) -> int:
        rows_list = list(rows)
        logger.debug("replace_rows ref_uri=%s new_rows=%d kind=%s", ref_uri, len(rows_list), value_kind)
        df = (
            self._prepare_frame(self._rows_frame(ref_uri, rows_list, value_kind))
            if rows_list
            else pl.DataFrame()
        )
        # One transaction for delete + insert: a failure leaves the old rows intact.
        with timed_debug(logger, "replace_rows ref_uri=%s rows=%d", ref_uri, len(df)), \
                self.conn.transaction(), self.conn.cursor() as cur:
            cur.execute(
                f"""
                DELETE FROM {TIMESERIES_TABLE}
                WHERE ref_id = (SELECT ref_id FROM {REF_IDS_TABLE} WHERE ref_uri = %s)
                """,
                [ref_uri],
            )
            if df.is_empty():
                return 0
            return self._insert_frame(cur, df)

    def bulk_insert_polars(self, df: pl.DataFrame) -> int:
        """Upsert a Polars frame with columns ``ref_uri, ts, value[, value_kind]``
        or the already split ``ref_uri, ts, numeric_value, text_value``.

        Returns the number of rows merged (inserted or updated).
        """
        if df.is_empty():
            logger.debug("bulk_insert_polars: empty DataFrame, skipping")
            return 0
        in_rows = len(df)
        with timed_debug(logger, "bulk_insert_polars prepare/dedupe rows=%d", in_rows):
            df = self._prepare_frame(df)
        logger.debug("bulk_insert_polars: %d rows after dedupe (was %d)", len(df), in_rows)
        try:
            with timed_debug(logger, "bulk_insert_polars COPY+merge rows=%d", len(df)), \
                    self.conn.transaction(), self.conn.cursor() as cur:
                merged = self._insert_frame(cur, df)
        except Exception:
            logger.exception("acquirium: bulk insert into %s failed", TIMESERIES_TABLE)
            raise
        logger.info("acquirium: bulk inserted %d rows into %s", merged, TIMESERIES_TABLE)
        return merged

    @staticmethod
    def _rows_frame(ref_uri: str, rows_list: list[tuple[datetime, Any]], value_kind: str) -> pl.DataFrame:
        n = len(rows_list)
        return pl.DataFrame(
            {
                "ref_uri": pl.Series("ref_uri", [ref_uri] * n, dtype=pl.Utf8),
                "ts": pl.Series("ts", [ts for ts, _ in rows_list], dtype=pl.Datetime("us", "UTC")),
                "value": typed_value_series([value for _, value in rows_list]),
                "value_kind": pl.Series("value_kind", [value_kind] * n, dtype=pl.Utf8),
            }
        )

    @staticmethod
    def _prepare_frame(df: pl.DataFrame) -> pl.DataFrame:
        """Split value columns, normalise ts to tz-aware UTC, dedupe on (ref_uri, ts).

        Dedupe is required: ON CONFLICT DO UPDATE rejects a source that names
        the same row twice. Last occurrence wins, matching a sequence of
        individual upserts.
        """
        df = prepare_value_columns(df)
        ts = pl.col("ts")
        if df.schema["ts"].time_zone is None:
            # Naive timestamps are taken as UTC, matching _to_utc on the read side.
            ts = ts.dt.replace_time_zone("UTC")
        else:
            ts = ts.dt.convert_time_zone("UTC")
        df = df.with_columns(ts.cast(pl.Datetime("us", "UTC")))
        return df.unique(subset=["ref_uri", "ts"], keep="last", maintain_order=True)

    def _insert_frame(self, cur, df: pl.DataFrame) -> int:
        """Merge a prepared frame on *cur*. Call inside a transaction.

        The frame is serialised to CSV by Polars and handed to COPY in one
        write, so no per-row Python loop touches the data. Polars writes NULL
        as an empty field and an empty string as ``""``, which is exactly how
        COPY's CSV format tells the two apart; timestamps carry their UTC
        offset so the TIMESTAMPTZ column parses them unambiguously.
        """
        staging = self.STAGING_TABLE
        # DROP first: ON COMMIT DROP only fires at the outer commit, so a
        # second write inside one begin() span would otherwise find the table
        # still there.
        cur.execute(f"DROP TABLE IF EXISTS {staging}")
        cur.execute(
            f"""
            CREATE TEMP TABLE {staging} (
                ref_uri TEXT NOT NULL,
                ts TIMESTAMPTZ NOT NULL,
                numeric_value DOUBLE PRECISION,
                text_value TEXT
            ) ON COMMIT DROP
            """
        )
        payload = df.select(["ref_uri", "ts", "numeric_value", "text_value"]).write_csv(
            include_header=False
        )
        with timed_debug(logger, "COPY rows=%d bytes=%d", len(df), len(payload)):
            with cur.copy(
                f"COPY {staging} (ref_uri, ts, numeric_value, text_value) FROM STDIN WITH (FORMAT csv)"
            ) as copy:
                copy.write(payload)
        # WHERE NOT EXISTS rather than relying on ON CONFLICT alone: a
        # conflicting insert still draws a sequence value, and every batch
        # re-mentions its existing streams. ON CONFLICT stays as the guard for
        # two first writes racing.
        cur.execute(
            f"""
            INSERT INTO {REF_IDS_TABLE} (ref_uri)
            SELECT DISTINCT i.ref_uri FROM {staging} AS i
            WHERE NOT EXISTS (
                SELECT 1 FROM {REF_IDS_TABLE} AS r WHERE r.ref_uri = i.ref_uri
            )
            ON CONFLICT (ref_uri) DO NOTHING
            """
        )
        with timed_debug(logger, "merge into %s rows=%d", TIMESERIES_TABLE, len(df)):
            cur.execute(
                f"""
                INSERT INTO {TIMESERIES_TABLE} (ref_id, ts, numeric_value, text_value)
                SELECT r.ref_id, i.ts, i.numeric_value, i.text_value
                FROM {staging} AS i
                JOIN {REF_IDS_TABLE} AS r USING (ref_uri)
                ON CONFLICT (ref_id, ts) DO UPDATE SET
                    numeric_value = EXCLUDED.numeric_value,
                    text_value = EXCLUDED.text_value
                """
            )
        return cur.rowcount

    # -------------------- stream references --------------------
    def ensure_stream_ref(
        self,
        point_uri: str | None,
        source_id: str,
        ref_name: str,
        ref_uri: URIRef | None = None,
        value_kind: str = "text",
    ) -> URIRef:
        """Register a stream reference in the streams table.

        The ref URI is computed deterministically from (source_id, ref_name) via
        :func:`compute_ref_uri`, so two sources with the same ref_name never
        produce the same storage key. The ref URI is also used as the
        TimescaleDB row key for the stream's data. Pass a precomputed ref_uri
        to avoid recomputing it when already available.

        Returns the ref URI.
        """
        if ref_uri is None:
            ref_uri = compute_ref_uri(source_id, ref_name)
        value_kind = normalize_value_kind(value_kind)
        # logger.debug(
        #     "ensure_stream_ref source=%s ref_name=%s point_uri=%s kind=%s",
        #     source_id, ref_name, point_uri, value_kind,
        # )
        with self.conn.cursor() as cur:
            cur.execute(
                f"""
                INSERT INTO {STREAMS_TABLE} (ref_uri, point_uri, source_id, ref_name, value_kind)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (ref_uri) DO UPDATE
                    SET
                        point_uri = COALESCE(EXCLUDED.point_uri, {STREAMS_TABLE}.point_uri),
                        source_id = EXCLUDED.source_id,
                        ref_name = EXCLUDED.ref_name,
                        value_kind = EXCLUDED.value_kind
                """,
                (str(ref_uri), point_uri, source_id, ref_name, value_kind),
            )
        return ref_uri

    def ensure_stream_refs(
        self,
        refs: Iterable[tuple[str | None, str, str, str | None, str]],
    ) -> list[str]:
        """Batch form of :meth:`ensure_stream_ref`.

        Each entry is ``(point_uri, source_id, ref_name, ref_uri, value_kind)``.

        COPY into a staging table and upsert from it in one statement, rather
        than a statement per row: COPY streams the whole batch over the wire in
        a single command, which beats even a pipelined executemany.
        """
        prepared: dict[str, tuple[Any, ...]] = {}
        for point_uri, source_id, ref_name, ref_uri, value_kind in refs:
            key = str(ref_uri if ref_uri is not None else compute_ref_uri(source_id, ref_name))
            # Last occurrence wins, matching a sequence of individual upserts.
            # ON CONFLICT DO UPDATE also refuses a source naming the same row
            # twice, and the caller's SPARQL can legitimately yield repeats.
            prepared[key] = (key, point_uri, source_id, ref_name, normalize_value_kind(value_kind))
        if not prepared:
            return []
        cols = "(ref_uri, point_uri, source_id, ref_name, value_kind)"
        # The connection runs autocommit, so an explicit transaction is what keeps
        # the staging table alive from COPY through to the upsert (and drops it).
        with timed_debug(logger, "ensure_stream_refs rows=%d", len(prepared)), self.conn.transaction():
            with self.conn.cursor() as cur:
                cur.execute(
                    f"CREATE TEMP TABLE _acquirium_incoming_refs "
                    f"(LIKE {STREAMS_TABLE}) ON COMMIT DROP"
                )
                with cur.copy(f"COPY _acquirium_incoming_refs {cols} FROM STDIN") as copy:
                    for row in prepared.values():
                        copy.write_row(row)
                cur.execute(
                    f"""
                    INSERT INTO {STREAMS_TABLE} {cols}
                    SELECT ref_uri, point_uri, source_id, ref_name, value_kind
                    FROM _acquirium_incoming_refs
                    ON CONFLICT (ref_uri) DO UPDATE
                        SET
                            point_uri = COALESCE(EXCLUDED.point_uri, {STREAMS_TABLE}.point_uri),
                            source_id = EXCLUDED.source_id,
                            ref_name = EXCLUDED.ref_name,
                            value_kind = EXCLUDED.value_kind
                    """
                )
        return list(prepared.keys())

    def resolve_storage_key(self, point_uri: str) -> str:
        """Return the storage key (ref URI) for a point_uri, or point_uri itself if not registered.

        Streams inserted via insert_timeseries are stored under their ref URI.
        This resolves the semantic URI → ref URI so reads find the right rows.
        Falls back to the URI itself for data inserted directly (e.g. bulk CSV ingest).
        """
        with self.conn.cursor() as cur:
            cur.execute(
                f"SELECT ref_uri FROM {STREAMS_TABLE} WHERE point_uri = %s",
                (point_uri,),
            )
            row = cur.fetchone()
            return row[0] if row else point_uri

    def resolve_storage_keys(self, point_uris: list[str]) -> dict[str, str]:
        """Batch-resolve point_uris to storage keys in a single query.

        Returns a mapping of point_uri → ref_uri (or point_uri itself for
        unregistered URIs, preserving the single-URI fallback behaviour).
        """
        if not point_uris:
            return {}
        with timed_debug(logger, "resolve_storage_keys n=%d", len(point_uris)), self.conn.cursor() as cur:
            cur.execute(
                f"SELECT point_uri, ref_uri FROM {STREAMS_TABLE} WHERE point_uri = ANY(%s)",
                (point_uris,),
            )
            rows = cur.fetchall()
        registered = {row[0]: row[1] for row in rows}
        return {uri: registered.get(uri, uri) for uri in point_uris}

    # -------------------- queries --------------------
    def timeseries(
        self,
        ref_uri: str,
        *,
        start: datetime | None = None,
        end: datetime | None = None,
        limit: int | None = None,
        order: Order = "asc",
        batch_size: int = 50_000,
        value_mode: str = "default",
    ) -> Iterator[pa.RecordBatch]:
        '''
        Returns an iterator over the time series data for the given ref URI.
        '''
        mode = normalize_value_mode(value_mode)
        with self.conn.cursor() as cur:
            ref_id = self._ref_id(cur, ref_uri)
        if ref_id is None:
            # Never written to: no id, no rows.
            logger.debug("timeseries ref_uri=%s has no ref_id; yielding nothing", ref_uri)
            return
        clauses = ["ref_id = %s"]
        params: list[Any] = [ref_id]

        if start:
            clauses.append("ts >= %s")
            params.append(self._to_utc(start))
        if end:
            clauses.append("ts <= %s")
            params.append(self._to_utc(end))
        if mode == "numeric":
            clauses.append("numeric_value IS NOT NULL")
        elif mode == "text":
            clauses.append("text_value IS NOT NULL")

        where = " AND ".join(clauses)
        order_sql = "ASC" if order == "asc" else "DESC"
        limit_sql = " LIMIT %s" if limit else ""
        if limit:
            params.append(limit)

        query = f"""
            SELECT
                ts,
                numeric_value,
                text_value
            FROM {TIMESERIES_TABLE}
            WHERE {where}
            ORDER BY ts {order_sql}{limit_sql}
        """

        value_kind = self.stream_value_kind(str(ref_uri))
        logger.debug(
            "timeseries ref_uri=%s start=%s end=%s limit=%s order=%s mode=%s",
            ref_uri, start, end, limit, order, mode,
        )
        with self.conn.cursor() as cur:
            with timed_debug(logger, "timeseries cur.execute ref_uri=%s", ref_uri):
                cur.execute(query, params)

            total = 0
            while True:
                rows = cur.fetchmany(batch_size)
                if not rows:
                    logger.debug("timeseries ref_uri=%s yielded total rows=%d", ref_uri, total)
                    break
                total += len(rows)

                ts_col = [r[0] for r in rows]
                numeric_col = [r[1] for r in rows]
                text_col = [r[2] for r in rows]
                ref_uri_col = [ref_uri] * len(ts_col)
                if not ts_col or not ref_uri_col:
                    break
                if mode == "coalesce":
                    values = [
                        text if text is not None else (str(numeric) if numeric is not None else None)
                        for numeric, text in zip(numeric_col, text_col)
                    ]
                    val_array = pa.array(values, type=pa.string())
                elif mode == "text" or value_kind == "text":
                    val_array = pa.array(text_col, type=pa.string())
                elif mode == "numeric" or value_kind == "numeric":
                    val_array = pa.array(numeric_col, type=pa.float64())
                elif any(v is not None for v in numeric_col):
                    val_array = pa.array(numeric_col, type=pa.float64())
                else:
                    val_array = pa.array(text_col, type=pa.string())

                batch = pa.record_batch(
                    [
                        pa.array(ts_col, type=pa.timestamp("us", tz="UTC")),
                        val_array,
                        pa.array(ref_uri_col, type=pa.string()),
                    ],
                    names=["ts", "value", "uri"],
                )
                yield batch

    def timeseries_info(self, ref_uri: str) -> TimeseriesInfo:
        with timed_debug(logger, "timeseries_info ref_uri=%s", ref_uri), self.conn.cursor() as cur:
            cur.execute(
                f"""
                SELECT COUNT(*), MIN(ts), MAX(ts)
                FROM {TIMESERIES_TABLE} AS t
                JOIN {REF_IDS_TABLE} AS r USING (ref_id)
                WHERE r.ref_uri = %s
                """,
                (ref_uri,),
            )
            cnt, earliest, latest = cur.fetchone()
        return TimeseriesInfo(table=TIMESERIES_TABLE, row_count=cnt, earliest=earliest, latest=latest)

    def timeseries_info_batch(self, ref_uris: list[str]) -> dict[str, TimeseriesInfo]:
        """Return stats (row_count, earliest, latest) for multiple ref URIs in one query."""
        if not ref_uris:
            return {}
        with timed_debug(logger, "timeseries_info_batch n=%d", len(ref_uris)), self.conn.cursor() as cur:
            cur.execute(
                f"""
                SELECT r.ref_uri, COUNT(*), MIN(ts), MAX(ts)
                FROM {TIMESERIES_TABLE} AS t
                JOIN {REF_IDS_TABLE} AS r USING (ref_id)
                WHERE r.ref_uri = ANY(%s)
                GROUP BY r.ref_uri
                """,
                (ref_uris,),
            )
            rows = cur.fetchall()
        result: dict[str, TimeseriesInfo] = {}
        for uri, cnt, earliest, latest in rows:
            result[uri] = TimeseriesInfo(table=TIMESERIES_TABLE, row_count=cnt, earliest=earliest, latest=latest)
        for uri in ref_uris:
            if uri not in result:
                result[uri] = TimeseriesInfo(table=TIMESERIES_TABLE, row_count=0)
        return result

    # -------------------- logging API --------------------

    def insert_log(self, log: LogEntry) -> None:
        point_uri: str = log.point_uri
        ts: datetime = log.timestamp
        message: str = log.message

        # if period is optional
        if log.period is None:
            observation_start = None
            observation_end = None
        else:
            observation_start = log.period.start
            observation_end = log.period.end

        if observation_start is not None and observation_end is not None:
            # Let Postgres build the range
            sql = f"""
                INSERT INTO {LOGS_TABLE} (point_uri, timestamp, observed, message)
                VALUES (%s, %s, tstzrange(%s, %s, '[)'), %s)
                ON CONFLICT (point_uri, timestamp) DO UPDATE SET message = EXCLUDED.message, observed = EXCLUDED.observed      
            """
            params = [point_uri, ts, observation_start, observation_end, message]
        elif observation_start is not None:
            sql = f"""
                INSERT INTO {LOGS_TABLE} (point_uri, timestamp, observed, message)
                VALUES (%s, %s, tstzrange(%s, 'infinity', '[)'), %s)
                ON CONFLICT (point_uri, timestamp) DO UPDATE SET message = EXCLUDED.message, observed = EXCLUDED.observed
            """
            params = [point_uri, ts, observation_start, message]
        elif observation_end is not None:
            sql = f"""
                INSERT INTO {LOGS_TABLE} (point_uri, timestamp, observed, message)
                VALUES (%s, %s, tstzrange('-infinity', %s, '[)'), %s)
                ON CONFLICT (point_uri, timestamp) DO UPDATE SET message = EXCLUDED.message, observed = EXCLUDED.observed
            """
            params = [point_uri, ts, observation_end, message]
        else:
            sql = f"""
                INSERT INTO {LOGS_TABLE} (point_uri, timestamp, observed, message)
                VALUES (%s, %s, NULL, %s)
                ON CONFLICT (point_uri, timestamp) DO UPDATE SET message = EXCLUDED.message, observed = EXCLUDED.observed
            """
            params = [point_uri, ts, message]
        
        logger.debug("insert_log point_uri=%s ts=%s", point_uri, ts)
        try:
            with self.conn.cursor() as cur:
                cur.execute(sql, params)
        except Exception as e:
            logger.error(f"An error occurred while inserting log: {e}")
            logger.error(f"SQL: {sql}")
            logger.error(f"Params: {params}")
            raise e
    def query_logs(
        self,
        point_uri: str,
        log_time_interval: TimeIntervalModel | None = None,
        obs_time_interval: TimeIntervalModel | None = None
    ) -> list[LogEntry]:
        start = log_time_interval.start if log_time_interval else None
        end = log_time_interval.end if log_time_interval else None
        observation_start = obs_time_interval.start if obs_time_interval else None
        observation_end = obs_time_interval.end if obs_time_interval else None
        
        clauses = ["point_uri = %s"]
        params: list[Any] = [point_uri]

        if start is not None:
            clauses.append("timestamp >= %s")
            params.append(start)
        if end is not None:
            clauses.append("timestamp <= %s")
            params.append(end)

        # observed overlap semantics with open ended windows
        if observation_start is not None and observation_end is not None:
            clauses.append("observed && tstzrange(%s, %s, '[)')")
            params.extend([observation_start, observation_end])
        elif observation_start is not None:
            clauses.append("observed && tstzrange(%s, 'infinity', '[)')")
            params.append(observation_start)
        elif observation_end is not None:
            clauses.append("observed && tstzrange('-infinity', %s, '[)')")
            params.append(observation_end)
        where = " AND ".join(clauses)
        query = f"""
            SELECT point_uri, timestamp, observed, message
            FROM {LOGS_TABLE}
            WHERE {where}
            ORDER BY timestamp ASC
        """
        try:
            with timed_debug(logger, "query_logs point_uri=%s clauses=%d", point_uri, len(clauses)), self.conn.cursor() as cur:
                cur.execute(query, params)
                rows = cur.fetchall()

            result: list[LogEntry] = []
            for point_uri, ts, observed_range, msg in rows:
                print(point_uri, ts, observed_range, msg)
                period = None
                if observed_range is not None:
                    period = TimeIntervalModel(start=observed_range.lower, end=observed_range.upper)
                else:
                    period = TimeIntervalModel(start=None, end=None)

                result.append(
                    LogEntry(
                        point_uri=point_uri,
                        timestamp=ts,
                        period=period,
                        message=msg,
                    )
                )
            return result
        except Exception as e:
            logger.error(f"An error occurred while querying logs: {e}")
            logger.error(f"Query: {query}")
            return []

    def delete_logs(self, point_uri: str) -> None:
        logger.debug("delete_logs point_uri=%s", point_uri)
        with self.conn.cursor() as cur:
            cur.execute(f"DELETE FROM {LOGS_TABLE} WHERE point_uri=%s", (point_uri,))
        return True

    # -------------------- transaction helpers --------------------
    def begin(self) -> None:
        if not self._in_tx:
            logger.debug("BEGIN")
            self.conn.autocommit = False
            self._in_tx = True
            self.conn.execute("BEGIN")

    def commit(self) -> None:
        if self._in_tx:
            logger.debug("COMMIT")
            self.conn.commit()
            self.conn.autocommit = True
            self._in_tx = False

    def rollback(self) -> None:
        if self._in_tx:
            logger.debug("ROLLBACK")
            self.conn.rollback()
            self.conn.autocommit = True
            self._in_tx = False

    # -------------------- utility --------------------
    def sql_query(self, query: str) -> dict[str, Any]:
        logger.debug("sql_query: %s", query.replace("\n", " ")[:200])
        with timed_debug(logger, "sql_query"), self.conn.cursor() as cur:
            cur.execute(query)
            cols = [desc[0] for desc in cur.description] if cur.description else []
            rows = cur.fetchall() if cur.description else []
        return {"columns": cols, "rows": rows}

    # -------------------- lifecycle --------------------
    def close(self) -> None:
        logger.debug("TimescaleStore.close")
        self.conn.close()

    # -------------------- helpers --------------------
    def _to_utc(self, ts: datetime) -> datetime:
        if ts.tzinfo is None:
            return ts.replace(tzinfo=timezone.utc)
        return ts.astimezone(timezone.utc)

    def _to_str(self, val: Any) -> str | None:
        if val is None:
            return None
        return str(val)

    def stream_value_kind(self, ref_uri: str) -> str | None:
        with self.conn.cursor() as cur:
            cur.execute(
                f"SELECT value_kind FROM {STREAMS_TABLE} WHERE ref_uri = %s",
                (ref_uri,),
            )
            row = cur.fetchone()
        return row[0] if row else None
