import json
from grafanalib._gen import DashboardEncoder
import requests
def get_dashboard_json(dashboard, overwrite=True, message="Update"):
    '''
    get_dashboard_json generates JSON from grafanalib Dashboard object

    :param dashboard - Dashboard() created via grafanalib
    '''
    

    # grafanalib generates json which need to pack to "dashboard" root element
    return json.dumps(
        {
            "dashboard": dashboard.to_json_data(),
            "overwrite": overwrite,
            "message": message
        }, sort_keys=True, indent=2, cls=DashboardEncoder)

def upload_to_grafana(json, server, api_key, verify=True):
    '''
    upload_to_grafana tries to upload dashboard to grafana and prints response

    :param json - dashboard json generated by grafanalib
    :param server - grafana server name
    :param api_key - grafana api key with read and write privileges
    '''

    headers = {'Authorization': f"Bearer {api_key}", 'Content-Type': 'application/json'}
    # print(json)
    r = requests.post(f"http://{server}/api/dashboards/db", data=json, headers=headers, verify=verify)
    # TODO: add error handling
    # print(f"{r.status_code} - {r.content}")
    # with open("response.json", "w") as f:
    #     import json
    #     f.write(json.dumps(r.json(), indent=4))

def upload_dashboard(dashboard, server, api_key, verify=True):
    json = get_dashboard_json(dashboard)
    # json = json.replace("\"showThresholdLabels\": false", "\"showThresholdLabels\": true")
    # print(json)
    upload_to_grafana(json, server, api_key, verify)